---
- name: Set Passwords
  hosts: localhost
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: "vcenter_password"
      prompt: "Enter password for {{ vcenter_username }} - {{ vcenter_hostname }}"
      private: yes
    - name: "new_password"
      prompt: "Enter new password for Windows local administrator account"
      private: yes
    - name: "domain_join_password"
      prompt: "Enter the password for domain user {{ ad_domain}} - {{domain_join_username}}"
      private: yes
  tasks:
    - set_fact:
        vcenter_password: "{{ vcenter_password }}"
        new_password: "{{ new_password }}"
        domain_join_password: "{{ domain_join_password }}"

- name: Build Windows Environment
  hosts: win
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/main.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
    - new_password: "{{ hostvars['localhost']['new_password'] }}"
    - domain_join_password: "{{ hostvars['localhost']['domain_join_password'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_windows/main.yml
  serial: 1

- name: Build Linux Environment
  hosts: lin
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
      - include_vars: vars/main.yml
  vars:
    - vcenter_password: "{{ hostvars['localhost']['vcenter_password'] }}"
    - domain_join_password: "{{ hostvars['localhost']['domain_join_password'] }}"
  tasks:
    - import_tasks: tasks/vmware_create_linux/main.yml
  serial: 1